[build-system]
requires = ["hatchling >= 1.26",
            "paho-mqtt ~= 2.1.0"]
build-backend = "hatchling.build"
[project]
name = "comet-wifi-communicator"
version = "0.3.0"
authors = [
  { name="zerog981", email="zerog981@example.com" },
]
description = "A library for communicating with Comet WiFi Thermostats over LAN."
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-or-later"
license-files = ["LICEN[CS]E*"]

packages = ["src/comet-wifi-communicator"]

[project.optional-dependencies]
dev = [
    "pytest>=9.0",
    "pytest-asyncio>=1.3",
    "pytest-mock>=3.15",
    "pytest-cov>=7.1",
    "bandit>=1.9",
    "pre-commit>=4.5",
]

[project.urls]
Homepage = "https://github.com/zerog981/Comet-WiFi-Communicator"
Issues = "https://github.com/"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
asyncio_mode = "auto"
markers = [
    "asyncio: marks tests as async (deselect with '-m \"not asyncio\"')",
]

[tool.coverage.run]
source = ["src"]
omit = ["*/tests/*"]

[tool.ruff]
required-version = ">=0.15.1"

[tool.bandit]
exclude_dirs = ["tests"]

[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
branch = 'main'
changelog_file = 'CHANGELOG.md'
build_command = 'python -m pip install -r requirements_dev.txt && python -m build'
allow_zero_version = true