[build-system]
requires = ["hatchling >= 1.26",
            "paho-mqtt ~= 2.1.0"]
build-backend = "hatchling.build"
[project]
name = "comet-wifi-communicator"
version = "0.0.5"
authors = [
  { name="zerog981", email="zerog981@example.com" },
]
description = "A library for communicating with Comet WiFi Thermostats over LAN."
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-or-later"
license-files = ["LICEN[CS]E*"]

packages = ["src/comet-wifi-communicator"]

[project.urls]
Homepage = "https://github.com/"
Issues = "https://github.com/"