name: ci-cd
on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v6

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install required packages
        run: python -m pip install -r requirements_dev.txt

      - name: Perform Bandit Analysis
        run: python -m bandit -r -x "tests" src

      - name: Run unit tests
        run: python -m pytest -v --cov --cov-fail-under=90 --cov-report=term-missing

  cd-build:
    permissions:
      contents: write
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
      released: ${{ steps.release.outputs.released }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Checkout full repository for versioning

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Prepare new release
        uses: python-semantic-release/python-semantic-release@v10.5.3
        id: release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        if: steps.release.outputs.released == 'true'
        with:
          name: python-package-distributions
          path: dist/

  cd-publish-testpypi:
    permissions:
      id-token: write
      contents: read
    needs: cd-build
    if: needs.cd-build.outputs.released == 'true'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ needs.cd-build.outputs.version }}
      released: ${{ needs.cd-build.outputs.released }}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v6

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish package TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: needs.cd-build.outputs.released == 'true'
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Purge pip cache
        run: pip cache purge

      - name: Test install from TestPyPI
        run: pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple --no-cache-dir --force-reinstall comet-wifi-communicator

      - name: Verify that latest version got installed
        run: |
          INSTALLED_VERSION=$(pip show comet-wifi-communicator | grep Version | awk '{print $2}') 
          LATEST_VERSION=${{ needs.cd-build.outputs.version }}
          if [ "$INSTALLED_VERSION" != "$LATEST_VERSION" ]; then
            echo "ERROR: Installed version $INSTALLED_VERSION does not match released version $LATEST_VERSION"
            exit 1
          fi
          echo "✓ Verified: comet-wifi-communicator $INSTALLED_VERSION installed correctly -> Upload valid."

  cd-publish-pypi:
    permissions:
      id-token: write
      contents: read
    needs: cd-publish-testpypi
    if: needs.cd-publish-testpypi.outputs.released == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v6

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: needs.cd-publish-testpypi.outputs.released == 'true'
